language: node_js
node_js:
  - "lts/*"

jobs:
  include:
    - stage: initialize
      script: npm run init
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build
