language: node_js
node_js:
  - "lts/*"

jobs:
  include:
    - stage: install
      script: npm install
    - stage: start
      script: npm run start
    - stage: test
      script: npm run test
    - stage: build
      script: npm run build
