language: node_js
node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: setup
      script: yarn
    - stage: test
      script: yarn test
    - stage: build
      script: yarn build
